# This file contains values from Cookiecutter

default_context:
  project_name: "data-eng-bent-oak-task"
  project_description: "Task for data visualization specialist job position in betn oak systems."
  organization: "bent-oak"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "rezashabrang"
  email: "rezashabrang.m@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
